### ISSUE TITLE
raise KeyError(key) from None

### ISSUE THREAD

**Issue by qinqoushui** [Xuchengen/rocketmq-docker-build#13]
我尝试使用你的main.py来自行编译一个DOCKER，因为我需要在ARM和LOONGARCH上使用。
我使用CENTOS9+PYTHON3.9.20,和UBUNTU 22+PYTHON3.10，都得到了同样的失败提示
希望能得到你的帮助
```
sudo python3 main.py 
⚠️警告：当前操作系统没有Maven环境，本程序将初始化一个内置Maven环境！
Traceback (most recent call last):
  File "/home/zy/mq/rocketmq-docker-build-master/main.py", line 114, in <module>
    main()
  File "/home/zy/mq/rocketmq-docker-build-master/main.py", line 12, in main
    app_env_check()
  File "/home/zy/mq/rocketmq-docker-build-master/main.py", line 87, in app_env_check
    Maven.install()
  File "/home/zy/mq/rocketmq-docker-build-master/maven.py", line 73, in install
    Helper.progress("安装maven", Maven.__install)
  File "/home/zy/mq/rocketmq-docker-build-master/helper.py", line 173, in progress
    return future.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/zy/mq/rocketmq-docker-build-master/maven.py", line 69, in __install
    Maven.__install()
  File "/home/zy/mq/rocketmq-docker-build-master/maven.py", line 60, in __install
    os.environ["Path"] = os.environ["Path"] + os.pathsep + str(path_maven.joinpath("bin"))
  File "/usr/lib/python3.10/os.py", line 680, in __getitem__
    raise KeyError(key) from None
KeyError: 'Path'
```

**Comment by qinqoushui** [comment]
我放弃了，重新封装了，支持ARM和LOONGARCH，开始试用，看看能不能正常收发消息。qoushui/rocketmq
